### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by ValuedMammal**

### CODE REVIEW

**Comment by rustaceanrob** [comment]
Looks good, but let's use `cargo clippy --all-targets` to also lint tests and examples

**Comment by rustaceanrob** [comment]
makes sense, mostly referring to the changes in `tests/client.rs` that remove the use of `first`. could you rebase and pick up the changes on master for that?

**Comment by ValuedMammal** [comment]
As far as I know changing `first` to `iter().next()` was a fix for msrv

**Comment by rustaceanrob** [comment]
i see, rust `1.66`. thanks

**Pull request merged**
